const C=document.getElementById('game'),X=C.getContext('2d');X.imageSmoothingEnabled=false;const T=32,W=20,H=13;
const concepts={imagination:['Sociological Imagination','Connecting individual experiences with larger social forces and historical or institutional conditions.'],functionalism:['Functionalism','A perspective emphasizing social structures, functions, stability, and dysfunctions.'],conflict:['Conflict Theory','A perspective emphasizing inequality, power, competing interests, and control over resources.'],interaction:['Symbolic Interactionism','A perspective emphasizing meanings, symbols, identities, and everyday interaction.'],methods:['Research Methods','Systematic strategies for gathering and analyzing evidence about social life.'],sampling:['Sampling','Selecting people or cases from a population so evidence is not based only on whoever is easiest to reach.'],validity:['Validity','The extent to which a measure captures what it claims to measure.'],ethics:['Research Ethics','Principles such as informed participation, privacy, minimizing harm, and responsible treatment of participants.']};
const fresh=()=>({char:{name:'Alex',pronouns:'They/Them',role:'College student & part-time worker',transport:'Public transportation',sprite:'green'},x:9,y:10,quest:0,talked:{},unlocked:[],stats:{Resources:55,'Social Capital':50,'Institutional Access':55,Agency:55,Stress:35}});let S=JSON.parse(localStorage.getItem('socialLife03')||'null')||fresh();const save=()=>localStorage.setItem('socialLife03',JSON.stringify(S));
const map=["####################","#....TT....#........#","#....TT....#..CCCC..#","#..........#..CCCC..#","#..PPPP....#........#","#..PPPP....######.###","#.............==....#","#####.#####...==....#","#.........#...==....#","#..SS.....#.........#","#..SS...............#","#...................#","####################"];
const npcs=[{id:'maya',name:'Maya',x:5,y:6,c:'#d96b59'},{id:'lee',name:'Mr. Lee',x:15,y:4,c:'#d4b05d'},{id:'jordan',name:'Jordan',x:16,y:9,c:'#7a78d0'},{id:'burns',name:'Professor Burns',x:8,y:3,c:'#4f8f68'}];
const interactables=[{id:'notice',x:12,y:6},{id:'bus',x:18,y:7}];let dlg=null;
function unlock(k){if(k&&!S.unlocked.includes(k)){S.unlocked.push(k);save();renderUI()}}
function tile(x,y){return map[y]?.[x]||'#'}function walkable(x,y){return !'#TCPS'.includes(tile(x,y))&&!npcs.some(n=>n.x===x&&n.y===y)}
function rect(x,y,w,h,c){X.fillStyle=c;X.fillRect(x,y,w,h)}function px(x,y,c){rect(x*T,y*T,T,T,c)}
function drawMap(){for(let y=0;y<H;y++)for(let x=0;x<W;x++){let q=tile(x,y);px(x,y,q==='#'?'#31543a':q==='='?'#c6ad78':'#76a957');if(q==='T'){px(x,y,'#295b34');rect(x*T+8,y*T+5,16,22,'#173e25')}if(q==='C'){px(x,y,'#8d6049');rect(x*T+3,y*T+3,26,26,'#bd8a62')}if(q==='P'){px(x,y,'#6f7d78');rect(x*T+2,y*T+2,28,28,'#8c9994')}if(q==='S'){px(x,y,'#4b7181');rect(x*T+2,y*T+2,28,28,'#6f9aaa')}}
// roads, labels, small details
rect(0,192,640,8,'#e6d49b');rect(352,0,8,416,'#e6d49b');X.fillStyle='#10271f';X.font='bold 12px monospace';X.fillText('PARK',102,153);X.fillText('COFFEE',450,82);X.fillText('CAMPUS',94,306);X.fillText('BUS',560,247);
interactables.forEach(o=>{if(o.id==='notice'){rect(o.x*T+11,o.y*T+5,10,20,'#f0e5bd');rect(o.x*T+9,o.y*T+23,14,3,'#6d4a31')}else{rect(o.x*T+4,o.y*T+6,24,18,'#d4c448');rect(o.x*T+8,o.y*T+10,16,10,'#335a6d')}});npcs.forEach(drawNPC);drawPlayer();drawMarkers()}
function drawNPC(n){let a=n.x*T,b=n.y*T;rect(a+10,b+6,12,10,'#d6aa83');rect(a+8,b+16,16,12,n.c);rect(a+8,b+28,6,4,'#1d2622');rect(a+18,b+28,6,4,'#1d2622')}
function drawPlayer(){let colors={green:'#2d7653',blue:'#416b9b',red:'#a34f4b',purple:'#70528f'},a=S.x*T,b=S.y*T;rect(a+10,b+5,12,10,'#d4a27c');rect(a+8,b+15,16,13,colors[S.char.sprite]||colors.green);rect(a+8,b+28,6,4,'#17211c');rect(a+18,b+28,6,4,'#17211c')}
function relevant(id){if(S.quest===0)return id==='burns';if(S.quest===1)return ['maya','lee','jordan'].includes(id)&&!S.talked[id];if(S.quest===2)return id==='notice';if(S.quest===3)return id==='burns';if(S.quest===4)return id==='bus';if(S.quest===5)return id==='burns';return false}
function drawMarkers(){X.font='bold 18px monospace';X.textAlign='center';X.fillStyle='#ffe56c';[...npcs,...interactables].forEach(o=>{if(relevant(o.id))X.fillText('!',o.x*T+16,o.y*T-2)});X.textAlign='left'}
function loop(){drawMap();requestAnimationFrame(loop)}
function nearby(){return [...npcs,...interactables].find(o=>Math.abs(o.x-S.x)+Math.abs(o.y-S.y)<=1)}
function move(dx,dy){if(dlg)return;let nx=S.x+dx,ny=S.y+dy;if(walkable(nx,ny)){S.x=nx;S.y=ny;save()}}
function say(speaker,text,choices=[]){dlg={speaker,text,choices};document.getElementById('dialogue').classList.remove('hidden');speakerEl.textContent=speaker;speech.textContent=text;choicesEl.innerHTML='';choices.forEach((c,i)=>{let b=document.createElement('button');b.className='choice';b.textContent=`${i+1}. ${c[0]}`;b.onclick=()=>{dlg=null;c[1]();};choicesEl.appendChild(b)});drawPortrait(speaker)}
function closeDlg(){dlg=null;document.getElementById('dialogue').classList.add('hidden')}
function drawPortrait(who){let p=document.getElementById('portrait');p.innerHTML='';let cv=document.createElement('canvas');cv.width=64;cv.height=64;cv.style.width='100%';cv.style.height='100%';let q=cv.getContext('2d');q.imageSmoothingEnabled=false;q.fillStyle='#183f30';q.fillRect(0,0,64,64);let hair=who.includes('Burns')?'#2c211d':who==='Maya'?'#3a251e':who==='Mr. Lee'?'#24221d':'#342747';q.fillStyle='#d6a17d';q.fillRect(18,14,30,34);q.fillStyle=hair;q.fillRect(14,8,38,13);q.fillRect(12,12,8,26);q.fillStyle='#171b18';q.fillRect(24,27,4,4);q.fillRect(39,27,4,4);q.fillRect(29,40,10,3);if(who.includes('Burns')){q.fillStyle='#f0eddf';q.fillRect(15,48,36,16);q.fillStyle='#377557';q.fillRect(29,48,8,16)}p.appendChild(cv)}
function interact(){if(dlg){if(!dlg.choices.length)closeDlg();return}let o=nearby();if(!o)return say('Narrator','There is nothing to interact with here.');if(o.id==='burns')return burns();if(o.id==='maya')return maya();if(o.id==='lee')return lee();if(o.id==='jordan')return jordan();if(o.id==='notice')return notice();if(o.id==='bus')return bus()}
function burns(){if(S.quest===0)say('Professor Burns',`Hey, ${S.char.name}. Before class, I want you to investigate a small change in Lakeview. The coffee shop changed its hours and work schedules this week. Don't start with a theory. Talk to people first.`,[['I’ll see what people are experiencing.',()=>{S.quest=1;save();closeDlg();renderUI()}]]);else if(S.quest===3)say('Professor Burns','You found three different experiences of the same change. What should we ask next?',[['What larger conditions make the change easier for some people than others?',()=>{unlock('imagination');S.quest=4;save();say('Professor Burns','Exactly. That is the sociological imagination: connecting personal experiences to social arrangements. Check the bus stop next.')}],['Which person has the best attitude?',()=>say('Professor Burns','Attitude might matter, but it does not explain why people face different constraints. Try zooming out.',[['Ask about larger conditions.',()=>{unlock('imagination');S.quest=4;save();closeDlg();renderUI()}]])]]);else if(S.quest===5)say('Professor Burns','Now interpret what you observed. Different theoretical perspectives ask different questions.',[['Who controls schedules and who bears the costs?',()=>{unlock('conflict');finishLens('Conflict theory directs attention to power and unequal control over resources.')}],['What functions and dysfunctions does the schedule create?',()=>{unlock('functionalism');finishLens('Functionalism asks how arrangements contribute to coordination—and when they become dysfunctional.')}],['How do people define a “reliable worker” or “good customer”?',()=>{unlock('interaction');finishLens('Symbolic interactionism examines meanings and labels produced in everyday interaction.')}]]);else say('Professor Burns','Keep exploring. Sociology gets interesting when the first explanation is not the last one.')}
function finishLens(msg){S.quest=6;save();say('Professor Burns',msg+` You have completed the first Lakeview investigation. The next chapter segment will turn your observations into a research question and test how sampling, validity, and ethics affect what we can claim.`,[['Finish the vertical slice.',()=>{unlock('methods');closeDlg();renderUI()}]])}
function mark(id){S.talked[id]=true;if(['maya','lee','jordan'].every(k=>S.talked[k]))S.quest=2;save();renderUI()}
function maya(){say('Maya','I work mornings here and take classes in the afternoon. The new schedule gives me more hours, but now I miss the bus that gets me to campus on time.',[['Ask about transportation.',()=>{mark('maya');say('Maya','The next bus is forty minutes later. A car would solve it, I guess—but I don’t have one.')}],['Thank her.',()=>{mark('maya');closeDlg()}]])}
function lee(){say('Mr. Lee','I own the shop. Rent and supply costs went up, and mornings were understaffed. I changed the schedule because I’m trying to keep the place open.',[['Ask who helped decide the new schedule.',()=>{mark('lee');say('Mr. Lee','I made the final call. I asked for availability, but I couldn’t give everyone what they wanted.')}],['Thank him.',()=>{mark('lee');closeDlg()}]])}
function jordan(){say('Jordan','Honestly? I like the new hours. I work remotely and come here before lunch. It feels calmer now. I didn’t realize the workers were having trouble with it.',[['Ask what changed for them.',()=>{mark('jordan');say('Jordan','Mostly convenience. I have flexible hours and drive here, so the change barely costs me anything.')}],['Thank them.',()=>{mark('jordan');closeDlg()}]])}
function notice(){if(S.quest<2)return say('Notice Board','A flyer lists the coffee shop’s new hours. You do not have enough context yet to know what the change means.');S.quest=3;save();say('Observation','The same schedule change produces different consequences depending on work authority, transportation, school schedules, and flexibility. Professor Burns wanted you to observe before explaining.',[['Return to Professor Burns.',()=>{closeDlg();renderUI()}]])}
function bus(){if(S.quest!==4)return say('Bus Stop','A route map shows buses arriving at fixed intervals.');S.quest=5;save();say('Bus Stop','The route serves campus and Lakeview, but service becomes less frequent after the morning rush. A private workplace decision intersects with a public transportation schedule.',[['Return to Professor Burns.',()=>{closeDlg();renderUI()}]])}
function renderUI(){sideName.textContent=S.char.name;location.textContent='Lakeview';let qs=[['Meet Professor Burns','Find Professor Burns in the park.'],['Listen Before Explaining','Talk with Maya, Mr. Lee, and Jordan.'],['Compare Accounts','Inspect the notice near the road.'],['Zoom Out','Return to Professor Burns.'],['Follow the Connection','Inspect the bus stop.'],['Choose a Lens','Return to Professor Burns.'],['Investigation Complete','Explore or review your journal.']];questTitle.textContent=qs[Math.min(S.quest,6)][0];objective.textContent=qs[Math.min(S.quest,6)][1];questSteps.innerHTML=qs.slice(0,6).map((q,i)=>`<div class="step ${i<S.quest?'done':''}">${i+1}. ${q[0]}</div>`).join('');stats.innerHTML=Object.entries(S.stats).map(([k,v])=>`<div class="stat">${k}<div class="bar"><i style="width:${v}%"></i></div></div>`).join('');journalCards.innerHTML=Object.entries(concepts).map(([k,v])=>`<div class="card ${S.unlocked.includes(k)?'':'locked'}"><h3>${S.unlocked.includes(k)?'✓':'🔒'} ${v[0]}</h3><p>${S.unlocked.includes(k)?v[1]:'Discover this concept through play.'}</p></div>`).join('')}
const speakerEl=document.getElementById('speaker'),speech=document.getElementById('speech'),choicesEl=document.getElementById('choices');document.addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(document.activeElement.tagName))return;if(dlg&&dlg.choices.length&&/^[1-4]$/.test(e.key)){let i=+e.key-1;if(dlg.choices[i])dlg.choices[i][1]();return}if(e.key===' '||e.key==='Enter'){e.preventDefault();interact();return}if(e.key==='ArrowUp'||e.key.toLowerCase()==='w')move(0,-1);if(e.key==='ArrowDown'||e.key.toLowerCase()==='s')move(0,1);if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')move(-1,0);if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')move(1,0)});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.getElementById(b.dataset.tab).classList.add('active')});
function fill(){name.value=S.char.name;pronouns.value=S.char.pronouns;role.value=S.char.role;transport.value=S.char.transport;sprite.value=S.char.sprite}saveChar.onclick=()=>{S.char={name:name.value.trim()||'Alex',pronouns:pronouns.value,role:role.value,transport:transport.value,sprite:sprite.value};save();renderUI();document.querySelector('[data-tab="play"]').click()};randomChar.onclick=()=>{let a=['Jordan','Maya','Taylor','Marcus','Riley','Sam','Avery','Cameron'];name.value=a[Math.floor(Math.random()*a.length)];pronouns.selectedIndex=Math.floor(Math.random()*pronouns.options.length);role.selectedIndex=Math.floor(Math.random()*role.options.length);transport.selectedIndex=Math.floor(Math.random()*transport.options.length);sprite.selectedIndex=Math.floor(Math.random()*sprite.options.length)};fill();renderUI();loop();
