const C=document.getElementById('game'),X=C.getContext('2d');X.imageSmoothingEnabled=false;const T=24,W=20,H=13;
const concepts={imagination:['Sociological Imagination','Connecting individual experiences with larger social forces and historical or institutional conditions.'],functionalism:['Functionalism','A perspective emphasizing social structures, functions, stability, and dysfunctions.'],conflict:['Conflict Theory','A perspective emphasizing inequality, power, competing interests, and control over resources.'],interaction:['Symbolic Interactionism','A perspective emphasizing meanings, symbols, identities, and everyday interaction.'],methods:['Research Methods','Systematic strategies for gathering and analyzing evidence about social life.'],sampling:['Sampling','Selecting people or cases from a population so evidence is not based only on whoever is easiest to reach.'],validity:['Validity','The extent to which a measure captures what it claims to measure.'],ethics:['Research Ethics','Principles such as informed participation, privacy, minimizing harm, and responsible treatment of participants.']};
const fresh=()=>({char:{name:'Alex',pronouns:'They/Them',role:'College student & part-time worker',transport:'Public transportation',sprite:'green'},x:9,y:10,quest:0,talked:{},unlocked:[],stats:{Resources:55,'Social Capital':50,'Institutional Access':55,Agency:55,Stress:35}});let S=JSON.parse(localStorage.getItem('socialLife03')||'null')||fresh();const save=()=>localStorage.setItem('socialLife03',JSON.stringify(S));
const map=["####################","#....TT....#........#","#....TT....#..CCCC..#","#..........#..CCCC..#","#..PPPP....#........#","#..PPPP....######.###","#.............==....#","#####.#####...==....#","#.........#...==....#","#..SS.....#.........#","#..SS...............#","#...................#","####################"];
const npcs=[{id:'maya',name:'Maya',x:5,y:6,c:'#b95249'},{id:'lee',name:'Mr. Lee',x:15,y:4,c:'#c59645'},{id:'jordan',name:'Jordan',x:16,y:9,c:'#635b9c'},{id:'burns',name:'Professor Burns',x:8,y:3,c:'#35694d'}];
const interactables=[{id:'notice',x:12,y:6},{id:'bus',x:18,y:7}];let dlg=null;
function unlock(k){if(k&&!S.unlocked.includes(k)){S.unlocked.push(k);save();renderUI()}}
function tile(x,y){return map[y]?.[x]||'#'}function walkable(x,y){return !'#TCPS'.includes(tile(x,y))&&!npcs.some(n=>n.x===x&&n.y===y)}
function r(x,y,w,h,c){X.fillStyle=c;X.fillRect(x|0,y|0,w|0,h|0)}
function dot(x,y,c){r(x,y,1,1,c)}
function grass(x,y){let a=x*T,b=y*T;r(a,b,T,T,'#6f9d4d');r(a,b+18,T,6,'#668f46');if((x*7+y*11)%4===0){r(a+4,b+6,2,1,'#92b85d');dot(a+5,b+5,'#a8c86d');r(a+16,b+15,2,1,'#4e773b')}if((x*13+y*3)%6===0){dot(a+19,b+7,'#d7ca68');dot(a+18,b+8,'#557f3d')}}
function tree(x,y){let a=x*T,b=y*T;r(a,b,T,T,'#6f9d4d');r(a+10,b+13,5,11,'#68452c');r(a+8,b+14,3,8,'#815837');r(a+3,b+5,18,13,'#21492f');r(a+1,b+9,22,8,'#285c36');r(a+5,b+2,15,11,'#397b42');r(a+8,b+1,9,5,'#4f914b');r(a+5,b+7,5,3,'#5c9d50');r(a+14,b+5,4,3,'#183b27');r(a+4,b+15,16,3,'#193e29')}
function pathTile(x,y){let a=x*T,b=y*T;r(a,b,T,T,'#c9b17c');r(a,b+3,T,2,'#d7c38f');r(a,b+19,T,2,'#aa8e60');for(let i=0;i<3;i++){let xx=a+3+((x*11+y*7+i*7)%18), yy=b+6+((x*5+y*13+i*5)%10);r(xx,yy,3,1,'#b49a69')}}
function buildingTile(x,y,q){let a=x*T,b=y*T,c=q==='C'?['#b77b56','#7d4039','#e0b47d']:q==='P'?['#7e8b86','#455952','#b9d1bd']:['#4d7f95','#315c70','#b6d6d6'];r(a,b,T,T,c[0]);r(a,b+18,T,6,c[1]);r(a+3,b+4,8,8,c[2]);r(a+4,b+5,6,6,'#87b4b5');r(a+14,b+4,7,14,c[1]);r(a+16,b+6,3,10,'#d2b47b');r(a,b,24,2,'#dfc08c')}
function drawMap(){for(let y=0;y<H;y++)for(let x=0;x<W;x++){let q=tile(x,y);if(q==='#'||q==='T')tree(x,y);else if(q==='=')pathTile(x,y);else if('CPS'.includes(q))buildingTile(x,y,q);else grass(x,y)}
// richer 16-bit-style environmental overlays
r(0,6*T,20*T,4,'#ead49a');r(11*T,0,4,13*T,'#ead49a');
// awnings and roof accents
r(14*T,2*T,4*T,5,'#713d39');for(let xx=14*T;xx<18*T;xx+=12){r(xx,2*T+5,7,5,'#d36a54');r(xx+7,2*T+5,5,5,'#f0d7a0')}
r(3*T,4*T,4*T,5,'#41564f');r(3*T,4*T+5,4*T,3,'#71877a');r(3*T,9*T,2*T,5,'#294f63');
// shrubs, flowers, bench, lamp, sign details
for(let i=0;i<8;i++){let xx=18+i*8,yy=11*T+(i%2)*3;r(xx,yy,3,3,i%3===0?'#e99a8d':i%3===1?'#e2d36c':'#d9a5cf');dot(xx+1,yy+3,'#35643b')}
r(7*T,3*T+13,34,4,'#765033');r(7*T+4,3*T+17,4,9,'#4d3525');r(7*T+28,3*T+17,4,9,'#4d3525');
r(10*T+15,2*T+4,3,24,'#3f4a45');r(10*T+10,2*T,13,7,'#e7ce78');r(10*T+12,2*T+2,9,3,'#fff0a0');
X.fillStyle='#253629';X.font='bold 8px monospace';X.fillText('PARK',3*T+7,4*T-5);X.fillText('CAFE',14*T+16,2*T+17);X.fillText('CAMPUS',3*T+3,9*T+17);X.fillText('BUS',17*T+8,8*T-4);
interactables.forEach(o=>{let a=o.x*T,b=o.y*T;if(o.id==='notice'){r(a+8,b+3,8,16,'#f2e3b2');r(a+7,b+18,10,3,'#6d4a31');r(a+10,b+6,4,1,'#8c7251');r(a+9,b+10,6,1,'#8c7251');r(a+10,b+14,4,1,'#8c7251')}else{r(a+2,b+7,20,13,'#d6bd45');r(a+5,b+9,14,8,'#4e8090');r(a+7,b+11,10,4,'#9bc3c1');r(a+5,b+20,3,3,'#4c4130');r(a+16,b+20,3,3,'#4c4130')}});npcs.forEach(drawNPC);drawPlayer();drawMarkers()}
function personSprite(a,b,shirt,hair='#35271f',skin='#d5a079',accent='#ead7ad'){// 20x27 sprite centered in 24px tile
 r(a+6,b+2,12,3,hair);r(a+4,b+5,16,7,hair);r(a+6,b+7,12,9,skin);r(a+5,b+8,2,6,skin);r(a+18,b+8,2,6,skin);r(a+7,b+5,10,3,hair);r(a+5,b+5,4,6,hair);r(a+16,b+5,4,5,hair);
 r(a+8,b+10,2,2,'#2b2521');r(a+15,b+10,2,2,'#2b2521');dot(a+9,b+9,'#f3d4ad');dot(a+16,b+9,'#f3d4ad');r(a+11,b+14,4,1,'#9d6257');
 r(a+5,b+16,15,7,shirt);r(a+3,b+17,3,8,shirt);r(a+20,b+17,3,8,shirt);r(a+4,b+24,3,2,skin);r(a+19,b+24,3,2,skin);r(a+8,b+17,9,2,accent);r(a+7,b+23,5,4,'#344044');r(a+14,b+23,5,4,'#344044');r(a+6,b+27,6,2,'#262a2d');r(a+14,b+27,6,2,'#262a2d')}
function drawNPC(n){let a=n.x*T,b=n.y*T-5;let hair=n.id==='jordan'?'#302642':n.id==='burns'?'#3b2a22':n.id==='maya'?'#3b251f':'#29251f';let skin=n.id==='jordan'?'#9d684e':'#d5a079';personSprite(a,b,n.c,hair,skin);if(n.id==='burns'){// plaid shirt + side-parted hair
 r(a+5,b+16,15,7,'#426e56');r(a+8,b+17,2,6,'#d6d0b5');r(a+14,b+17,2,6,'#d6d0b5');r(a+5,b+19,15,1,'#243f34');r(a+7,b+3,9,2,'#4a3429');r(a+5,b+5,4,3,'#4a3429')}}
function drawPlayer(){let colors={green:'#347a59',blue:'#4d6fa2',red:'#ad5650',purple:'#73588f'};personSprite(S.x*T,S.y*T-5,colors[S.char.sprite]||colors.green,'#302823','#d5a079')}
function drawMarkers(){X.font='bold 22px monospace';X.textAlign='center';X.fillStyle='#ffe56c';X.strokeStyle='#513b2c';X.lineWidth=3;[...npcs,...interactables].forEach(o=>{if(relevant(o.id)){X.strokeText('!',o.x*T+12,o.y*T-7);X.fillText('!',o.x*T+12,o.y*T-7)}});X.textAlign='left'}
function relevant(id){if(S.quest===0)return id==='burns';if(S.quest===1)return ['maya','lee','jordan'].includes(id)&&!S.talked[id];if(S.quest===2)return id==='notice';if(S.quest===3)return id==='burns';if(S.quest===4)return id==='bus';if(S.quest===5)return id==='burns';return false}
function drawMarkers(){X.font='bold 18px monospace';X.textAlign='center';X.fillStyle='#ffe56c';[...npcs,...interactables].forEach(o=>{if(relevant(o.id))X.fillText('!',o.x*T+16,o.y*T-2)});X.textAlign='left'}
function loop(){drawMap();requestAnimationFrame(loop)}
function nearby(){return [...npcs,...interactables].find(o=>Math.abs(o.x-S.x)+Math.abs(o.y-S.y)<=1)}
function move(dx,dy){if(dlg)return;let nx=S.x+dx,ny=S.y+dy;if(walkable(nx,ny)){S.x=nx;S.y=ny;save()}}
function say(speaker,text,choices=[]){dlg={speaker,text,choices};document.getElementById('dialogue').classList.remove('hidden');speakerEl.textContent=speaker;speech.textContent=text;choicesEl.innerHTML='';choices.forEach((c,i)=>{let b=document.createElement('button');b.className='choice';b.textContent=`${i+1}. ${c[0]}`;b.onclick=()=>{dlg=null;c[1]();};choicesEl.appendChild(b)});drawPortrait(speaker)}
function closeDlg(){dlg=null;document.getElementById('dialogue').classList.add('hidden')}
function drawPortrait(who){let p=document.getElementById('portrait');p.innerHTML='';let cv=document.createElement('canvas');cv.width=48;cv.height=48;cv.style.width='100%';cv.style.height='100%';let q=cv.getContext('2d');q.imageSmoothingEnabled=false;let rr=(x,y,w,h,c)=>{q.fillStyle=c;q.fillRect(x,y,w,h)};rr(0,0,48,48,'#1f4534');rr(0,34,48,14,'#315f47');let burns=who.includes('Burns'),maya=who==='Maya',lee=who==='Mr. Lee',jordan=who==='Jordan';let hair=burns?'#3c2b24':maya?'#39251f':lee?'#29251f':'#312541';let skin=jordan?'#9d684e':'#d8a47e';rr(11,5,27,7,hair);rr(8,10,32,13,hair);rr(12,11,25,23,skin);rr(9,14,4,14,skin);rr(37,14,4,14,skin);rr(10,8,10,11,hair);rr(30,8,9,9,hair);rr(16,17,4,3,'#29231f');rr(30,17,4,3,'#29231f');rr(17,16,2,1,'#f0d0ad');rr(31,16,2,1,'#f0d0ad');rr(22,27,8,2,'#a46458');rr(14,34,23,14,burns?'#426e56':maya?'#a84f48':lee?'#b88c45':'#675c9b');if(burns){rr(17,34,3,14,'#d8d0b6');rr(29,34,3,14,'#d8d0b6');rr(14,39,23,2,'#294b3b');rr(12,7,15,3,'#4c362b')}}p.appendChild(cv)}
function interact(){if(dlg){if(!dlg.choices.length)closeDlg();return}let o=nearby();if(!o)return say('Narrator','There is nothing to interact with here.');if(o.id==='burns')return burns();if(o.id==='maya')return maya();if(o.id==='lee')return lee();if(o.id==='jordan')return jordan();if(o.id==='notice')return notice();if(o.id==='bus')return bus()}
function burns(){if(S.quest===0)say('Professor Burns',`Hey, ${S.char.name}. Before class, I want you to investigate a small change in Lakeview. The coffee shop changed its hours and work schedules this week. Don't start with a theory. Talk to people first.`,[['I’ll see what people are experiencing.',()=>{S.quest=1;save();closeDlg();renderUI()}]]);else if(S.quest===3)say('Professor Burns','You found three different experiences of the same change. What should we ask next?',[['What larger conditions make the change easier for some people than others?',()=>{unlock('imagination');S.quest=4;save();say('Professor Burns','Exactly. That is the sociological imagination: connecting personal experiences to social arrangements. Check the bus stop next.')}],['Which person has the best attitude?',()=>say('Professor Burns','Attitude might matter, but it does not explain why people face different constraints. Try zooming out.',[['Ask about larger conditions.',()=>{unlock('imagination');S.quest=4;save();closeDlg();renderUI()}]])]]);else if(S.quest===5)say('Professor Burns','Now interpret what you observed. Different theoretical perspectives ask different questions.',[['Who controls schedules and who bears the costs?',()=>{unlock('conflict');finishLens('Conflict theory directs attention to power and unequal control over resources.')}],['What functions and dysfunctions does the schedule create?',()=>{unlock('functionalism');finishLens('Functionalism asks how arrangements contribute to coordination—and when they become dysfunctional.')}],['How do people define a “reliable worker” or “good customer”?',()=>{unlock('interaction');finishLens('Symbolic interactionism examines meanings and labels produced in everyday interaction.')}]]);else say('Professor Burns','Keep exploring. Sociology gets interesting when the first explanation is not the last one.')}
function finishLens(msg){S.quest=6;save();say('Professor Burns',msg+` You have completed the first Lakeview investigation. The next chapter segment will turn your observations into a research question and test how sampling, validity, and ethics affect what we can claim.`,[['Finish the vertical slice.',()=>{unlock('methods');closeDlg();renderUI()}]])}
function mark(id){S.talked[id]=true;if(['maya','lee','jordan'].every(k=>S.talked[k]))S.quest=2;save();renderUI()}
function maya(){say('Maya','I work mornings here and take classes in the afternoon. The new schedule gives me more hours, but now I miss the bus that gets me to campus on time.',[['Ask about transportation.',()=>{mark('maya');say('Maya','The next bus is forty minutes later. A car would solve it, I guess—but I don’t have one.')}],['Thank her.',()=>{mark('maya');closeDlg()}]])}
function lee(){say('Mr. Lee','I own the shop. Rent and supply costs went up, and mornings were understaffed. I changed the schedule because I’m trying to keep the place open.',[['Ask who helped decide the new schedule.',()=>{mark('lee');say('Mr. Lee','I made the final call. I asked for availability, but I couldn’t give everyone what they wanted.')}],['Thank him.',()=>{mark('lee');closeDlg()}]])}
function jordan(){say('Jordan','Honestly? I like the new hours. I work remotely and come here before lunch. It feels calmer now. I didn’t realize the workers were having trouble with it.',[['Ask what changed for them.',()=>{mark('jordan');say('Jordan','Mostly convenience. I have flexible hours and drive here, so the change barely costs me anything.')}],['Thank them.',()=>{mark('jordan');closeDlg()}]])}
function notice(){if(S.quest<2)return say('Notice Board','A flyer lists the coffee shop’s new hours. You do not have enough context yet to know what the change means.');S.quest=3;save();say('Observation','The same schedule change produces different consequences depending on work authority, transportation, school schedules, and flexibility. Professor Burns wanted you to observe before explaining.',[['Return to Professor Burns.',()=>{closeDlg();renderUI()}]])}
function bus(){if(S.quest!==4)return say('Bus Stop','A route map shows buses arriving at fixed intervals.');S.quest=5;save();say('Bus Stop','The route serves campus and Lakeview, but service becomes less frequent after the morning rush. A private workplace decision intersects with a public transportation schedule.',[['Return to Professor Burns.',()=>{closeDlg();renderUI()}]])}
function renderUI(){sideName.textContent=S.char.name;location.textContent='Lakeview';let qs=[['Meet Professor Burns','Find Professor Burns in the park.'],['Listen Before Explaining','Talk with Maya, Mr. Lee, and Jordan.'],['Compare Accounts','Inspect the notice near the road.'],['Zoom Out','Return to Professor Burns.'],['Follow the Connection','Inspect the bus stop.'],['Choose a Lens','Return to Professor Burns.'],['Investigation Complete','Explore or review your journal.']];questTitle.textContent=qs[Math.min(S.quest,6)][0];objective.textContent=qs[Math.min(S.quest,6)][1];questSteps.innerHTML=qs.slice(0,6).map((q,i)=>`<div class="step ${i<S.quest?'done':''}">${i+1}. ${q[0]}</div>`).join('');stats.innerHTML=Object.entries(S.stats).map(([k,v])=>`<div class="stat">${k}<div class="bar"><i style="width:${v}%"></i></div></div>`).join('');journalCards.innerHTML=Object.entries(concepts).map(([k,v])=>`<div class="card ${S.unlocked.includes(k)?'':'locked'}"><h3>${S.unlocked.includes(k)?'✓':'🔒'} ${v[0]}</h3><p>${S.unlocked.includes(k)?v[1]:'Discover this concept through play.'}</p></div>`).join('')}
const speakerEl=document.getElementById('speaker'),speech=document.getElementById('speech'),choicesEl=document.getElementById('choices');document.addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(document.activeElement.tagName))return;if(dlg&&dlg.choices.length&&/^[1-4]$/.test(e.key)){let i=+e.key-1;if(dlg.choices[i])dlg.choices[i][1]();return}if(e.key===' '||e.key==='Enter'){e.preventDefault();interact();return}if(e.key==='ArrowUp'||e.key.toLowerCase()==='w')move(0,-1);if(e.key==='ArrowDown'||e.key.toLowerCase()==='s')move(0,1);if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')move(-1,0);if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')move(1,0)});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.getElementById(b.dataset.tab).classList.add('active')});
function fill(){name.value=S.char.name;pronouns.value=S.char.pronouns;role.value=S.char.role;transport.value=S.char.transport;sprite.value=S.char.sprite}saveChar.onclick=()=>{S.char={name:name.value.trim()||'Alex',pronouns:pronouns.value,role:role.value,transport:transport.value,sprite:sprite.value};save();renderUI();document.querySelector('[data-tab="play"]').click()};randomChar.onclick=()=>{let a=['Jordan','Maya','Taylor','Marcus','Riley','Sam','Avery','Cameron'];name.value=a[Math.floor(Math.random()*a.length)];pronouns.selectedIndex=Math.floor(Math.random()*pronouns.options.length);role.selectedIndex=Math.floor(Math.random()*role.options.length);transport.selectedIndex=Math.floor(Math.random()*transport.options.length);sprite.selectedIndex=Math.floor(Math.random()*sprite.options.length)};fill();renderUI();loop();
